[theme]
primaryColor = "#2962FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
